### ISSUE TITLE
idea上，打开多个项目，有可能点击飞机后，生成的文档不在当前项目上，在别的项目上

### ISSUE THREAD

**Issue by YouJieForGit** [kings1990/fast-request-doc#7]
### 当前使用版本(Current Version)
2.0.1
### 重现步骤(Repeat steps)
![image](https://user-images.githubusercontent.com/57011837/130747146-b3f0eded-30ab-472d-9040-d6982f118a2f.png)

**Comment by kings1990** [comment]
感谢反馈，找到问题了，多开窗口实例化的问题，下个版本给修复

**Comment by kings1990** [comment]
fix 2.0.2
