### ISSUE TITLE
Response窗口没有滚动条

### ISSUE THREAD

**Issue by ghost** [kings1990/fast-request-doc#9]
## 建议/改进(Suggestion/improvement)
eg: 接口返回结果都在一行上，然后就很长，但是有没有滚动条，就只能复制结果出来看，希望改进
![image](https://user-images.githubusercontent.com/21972139/132637948-8b2422b6-2080-473a-a6e7-82fb0832d79d.png)

**Comment by kings1990** [comment]
升级到2.0.4
